### ISSUE TITLE
Mint Error

### ISSUE THREAD

**Issue by ssdjet** [mxnster/masa-soulnames#1]
viktor@SVE:~/masa-soulnames-master$ node index
file:///home/viktor/masa-soulnames-master/index.js:147
                                console.log('Mint Error:', err?.reason)
                                                               ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by mxnster** [comment]
> viktor@SVE:~/masa-soulnames-master$ node index file:///home/viktor/masa-soulnames-master/index.js:147 console.log('Mint Error:', err?.reason) ^
> 
> SyntaxError: Unexpected token '.' at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18) at async link (internal/modules/esm/module_job.js:42:21)

I have released a small update. Please, check again
